title: Notes
#description: Cayman Blog Theme is a clean, responsive blogging theme for Jekyll and Gitlab/GitHub Pages.
show_downloads: false

baseurl: "/Notes" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://geosada.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: geosada
image: /thumbnail-jumbo.png

plugins:
  - jekyll-target-blank
  - jekyll-sitemap

target-blank:
    rel: nofollow

header_page_refs: ['top', 'about']
#header_page_refs: ['top']

# 250521 accrding to ChatGPT
markdown: kramdown
kramdown:
  # if you want GitHub-Flavored Markdown extensions (like tables), you can still use:
  input: GFM
  # tell kramdown to leave math code untouched for later processing
  math_engine: mathjax
  math_engine_opts:
    preview: true

